name = "LocalFennelPartitioning"
uuid = "bc5bb2de-b642-450c-9ee6-9b330b2022e0"
authors = ["P. Brayden Smith"]
version = "1.0.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
